# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o VcenterKiller.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: VcenterKiller
        path: ./
    - name: Add changes and push
      run: |
        git config --local user.email "1714985309@qq.com"
        git config --local user.name "ahr1i9"
        git add ./
        git commit -m "Add compiled binary"
        git push
