# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o VcenterKiller.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: VcenterKiller
        path: VcenterKiller.exe
    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1
      with:
        asset_path: ./VcenterKiller.exe
        asset_name: VcenterKiller.exe
        asset_content_type: application/octet-stream
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.release_id }}/assets?name=VcenterKiller.exe
        release_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        tag: v1.0  # 替换为您的发布标签
